require(shiny)
require(googleVis)
require(xlsx)
setwd("/Users/rrozas/Documents/Renault")
features <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 1)
roc <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 2)
alerts <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 3)
meteo <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 4)
km <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 5)
date_fab <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 6)
map <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 7)
words <-  read.xlsx(file = 'Data prototype Renault.xlsx', sheetIndex = 8)
AUC <- sum(roc$value_ROC)/100